import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { queueCapRecovery, RECOVERY_LIMITS, nextRecoveryBatch, worthwhile, type RecoveryYield } from './cap-recovery.js';
const db = new DatabaseSync(':memory:');
db.exec(`CREATE TABLE searches(zip TEXT PRIMARY KEY,city TEXT,latitude REAL,longitude REAL,distance_miles REAL,status TEXT,updated_at TEXT);
CREATE TABLE cap_recovery(parent_zip TEXT,child_zip TEXT,depth INTEGER,created_at TEXT,PRIMARY KEY(parent_zip,child_zip));
CREATE TABLE agents(license_number TEXT PRIMARY KEY,first_zip TEXT);
CREATE TABLE agent_zips(license_number TEXT,zip TEXT);
CREATE TABLE search_effort(zip TEXT PRIMARY KEY,seconds REAL);`);
db.prepare('INSERT INTO searches VALUES(?,?,?,?,?,?,?)').run('91506','Burbank',34.1728,-118.3235,0,'truncated','2026-10-08');
const first = queueCapRecovery(db,'91506',50);
assert.equal(first,2,'start with only two probes');
assert.equal(queueCapRecovery(db,'91506',50),0,'restart must not repeat parent expansion');
assert.equal((db.prepare("SELECT status FROM searches WHERE zip='91506'").get() as {status:string}).status,'truncated');
db.exec("UPDATE searches SET status='truncated'");
assert.equal(queueCapRecovery(db,'91506',50),0,'two low-yield probes stop expansion including recursion');
const children = db.prepare('SELECT child_zip FROM cap_recovery ORDER BY created_at,child_zip').all() as {child_zip:string}[];
for(let i=0;i<10;i++) {
  db.prepare('INSERT INTO agents VALUES(?,?)').run(String(i),children[1].child_zip);
  db.prepare('INSERT INTO agent_zips VALUES(?,?)').run(String(i),children[1].child_zip);
}
const productive = queueCapRecovery(db,'91506',50);
assert(productive>0,'productive completed probes permit follow-ups');
assert.equal(queueCapRecovery(db,'91506',50),0,'unfinished follow-ups block further expansion');
const sample = (status:string,new_agents:number,records=300):RecoveryYield=>({status,new_agents,records,child_zip:'test',seconds:0});
assert.equal(nextRecoveryBatch([]),2);
assert.equal(nextRecoveryBatch([sample('complete',0),sample('pending',0)]),0);
assert.equal(nextRecoveryBatch([sample('complete',0),sample('complete',0)]),0);
assert.equal(nextRecoveryBatch([sample('complete',10),sample('complete',0)]),1);
assert.equal(nextRecoveryBatch([sample('complete',10),sample('complete',0),sample('complete',0)]),0);
assert(worthwhile(sample('complete',5,100)),'5 percent threshold');
assert(!worthwhile(sample('complete',0,0)),'empty search is low yield');
assert.equal(nextRecoveryBatch(Array.from({length:8},()=>sample('complete',30))),0);
const max = db.prepare('SELECT MAX(depth) AS n FROM cap_recovery').get() as {n:number};
assert(max.n <= RECOVERY_LIMITS.depth,'recursive recovery must be bounded');
const count = db.prepare('SELECT COUNT(DISTINCT child_zip) AS n FROM cap_recovery').get() as {n:number};
assert(count.n <= RECOVERY_LIMITS.additionalZips);
console.log(`PASS: capped parent remains unresolved; ${first} first-level tasks, ${count.n} bounded total; restart idempotent.`);
db.close();
